#!/usr/bin/env sh

docker build                              \
  --build-arg _UNAME="spacemacser"        \
  --build-arg _GNAME="spacemacsians"      \
  --build-arg _UHOME="/home/spacemacs"    \
  --build-arg _UID="1000"                 \
  --build-arg _GID="1000"                 \
  --build-arg _WORKSPACE="/mnt/workspace" \
  -t $IMAGE_NAME .
